# Generated by Django 6.0.6 on 2026-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
